### get all figures
GET http://localhost:8080/webapi/figures

### get figure by id
GET http://localhost:8080/webapi/figures/8

### get figures designed by
GET http://localhost:8080/webapi/designers/1/figures

### create new figure
POST http://localhost:8080/webapi/figures
Content-Type: application/json
Authorization: Basic user1 user1

{
  "title": "Apocalypse Yesterday",
  "poster": "https://www.kinoteka.pl/img/logo.png",
  "rating": 4.5,
  "designerId": 3
}